= Couchbase Connect SF 2017 Demo Stage Script
:imagesdir: images
:icons: font
//:p_a: pass:q[[maroon]#icon:user[]^icon:comment[]^#]
//:p_b: pass:q[[green]#^icon:comment[flip="horizontal"]^icon:user[]#]
//:sd: icon:bolt[role="lime"]
//:td: pass:q[[red]#To do -#]
:p_a: pass:q[[maroon]#P-A#]
:p_b: pass:q[[green]#P-B#]
:sd: pass:q[[lime]#SD#]
:td: pass:q[[red]#To do -#]


== Outline

=== Story arc

Primary arc starts with discussion about how one presenter was recently ill.  Symptoms were uncertain, 
so they considered going to ER.  Through use of mobile app, they took temperature, opened case with provider's
on call system.  Nausea was issue, so on call care wanted to monitor fluid intake and weight loss 
(bluetooth scale, unstructured extra data). (Patient had flu shot from outside provider, AN knows). AN sent back information on signs to look out for, symptoms questionnaire,
options for contact.  Brief call where AN has patient information up and is able to suggest home care, reassure patient, 
set tracking schedule, set alerts, check for available appointment.

Patient follows up at appointment.  Doctor can see what treatments patient followed (other relevant data?).  
Doctor prescribes meds, has patient continue to monitor.  Mobile app has dose plan/reminders, keeps records automatically
fed back to provider (offline to online use).
Based on monitoring, patient sees progress, doctor is able to recommend when to taper off medication.

Switch to behind the scenes look.  See AN's dashboard with multi-patient view (cases opened/currently monitored)

.Note
Shows providing value-based care (focuses on outcome, improved patient experience because patient receives appropriate 
level of care without unnecessary ER visit, patient feels engaged while actually lowering overhead for care giver)
Show complexity of all information that comes together to provide care.

.Couchbase technology Highlights
* Mobile
** Data synced to device so e.g. can use in store to by recommended over-the-counter supplies
** Increased capability to integrate more sources
* Unstructured data
** Outside flu shot report integrated
*** N1QL query to discover this?
** Off-the-shelf vital sign equipment available (bluetooth scale, or heart rate monitor)
** FTS (hospital is seeing surge in reports of food poisoning, AN can choose to check this on the fly.)

.Drawbacks
* Doesn't address changing schema on the fly
* Story line too complex to follow?

Opportunities to highlight unstructured data: 

* Patient's primary care recently joined larger group, coding practices were different
* Data from vitals device added to mobile (Patient bought BT scale, app was able to integrate)
* BT scale data added easily

Opportunities to highlight FTS:

* Unclear whether food poisoning incident or flu (?). FTS against reports across provider network to check ?

Opportunities to highlight data integration

* Flu map
* Air quality map

=== Screens shown

==== P1
* Mobile app temperature
* AN open case dashboard
* AN patient detail view
* Couchbase operational dashboard

==== P2

* Doctor's view of patient record

==== P3

* Hospital administrator dashboard (graphs of unnecessary admissions or other analytics)

{sd} Presenter A on stage, finishes pre-demo talk.

{sd} Presenter B enters

{p_a} B, good to see you.  I was worried.  I heard you weren't feeling well and might not be able to be here.  You know I count on you.

{p_b} I was.  I'm feeling better now, but my doctor still wants to monitor me.  But I have to tell you, I had an amazing experience.

{p_a} What do you mean?

{p_b} I was really worried.  I had a fever, I had to run to the bathroom...

{p_a} TMI TMI!

{p_b} Yeah, you get the picture.  I thought I'd have go to the ER.

{p_a} Oooh, I hate that.  Sitting in a waiting room when you feel awful.  And half the time they just send you home.

{p_b} I know, I know.  Hold on though, you're going to love this.  I knew my doctor recently joined a network that uses Couchbase.

My wife has their mobile app.  Take a look at this patch she got to go with it.

{sd} Make show of handing over patch.

{p_a} It's just a little disc.  I don't see a battery.  What does it do?

{p_b} Yeah, you can read your temperature with it.  Super convenient.  Let me show you.

{sd} Takes patch back, reads temperature.

{p_b} See, check this out, temperature's back to normal.

With the app we were able to mark down symptoms, track my temperature, a whole bunch of things.  Then I set up to have an advice nurse call.

She was able to look at my vitals and the other info.  She knew I had a flew shot from the pharmacy already.  But her next question really surprised me.

She asked if I had eaten at a restaurant nearby.  Turns out the hospital had several cases of food poisoning that day.

{p_a} That's amazing.  So what happened.

{p_b} The nurse was able to send me a whole set of instructions on what I could do to control the symptoms, things to look out for to make sure 
I was ok.  She (?) said she'd keep monitoring me.  I was still sick, but I tell you, that was the best experience I've had.

It's like my care just flowed.  I was able to stay comfortable at home.  The next day I got a call from my doctor's office.  They had me in for a follow up that day.
My doctor wasn't in, but the one I saw had all my information, knew all about what advice I had followed, and everything.

{sd} Phone beeps, new alert shows

{p_b} Oh hey! He says everything is looking good.  I can start tapering off my medicine.  They'll send me reminders so I don't forget what dose to use.

{p_a} That's a lot of complex information moving around.  You said this is a group using Couchbase?

{sd} ~4 minutes to reach this point

{p_b} Let me show you what we built to (past shows have said "revolutionize"...) connected health.

.Note
Consideration:
Past demos end up as a walk through of UI, data, and code.

Mobile devices hard to demo.

The data in health care is complex.  

* Issues arise from difference in sources
** Examples
*** A practice wants to integrate with a hospital.  Two different EHR systems
*** New regulatory information
*** Updated clinical insights
*** Complete patient record comes from multiple service providers (labs, different specialists, often mix of provider networks, ...)
* Differences in definitions, quality
** Examples
*** Length of stay may be defined differently (ref: Health Catalyst)
*** Records (e.g. ER visit) often missing data
* Differences in consumption
** Example
*** X-ray image needed by physician, only needed as procedure code by billing

{td} Found some sources of sample EHR data to populate db.  Need to import.

{td} Diagram of interconnections: Sensor to phone to SG to CBS, CBS pulling data from other sources, different clients pulling data from CBS

{p_b} Let's start with the AN Dashboard.  This is where staff would monitor open cases.

{sd} Show dashboard

{td} N1QL query to create dashboard.  How can we demonstrate power of N1QL?  By showing different sources of same type of data (temperature readings could be automatic or hand-entered, or flu shot record could be unusual format or ...)

{td} Could show data integration (flu map from Everyday Health or other source confirming no local outbreak?)

{td} Keshav's "job loop" concept

Maybe there's a staff turnover time, with a briefing?

{sd} Drill down to individual patient view.  Show temperature graph, other vitals.  Show setting alerts?

{sd} Show FTS searching incident notes for something (restaurant name?)


Actors:

Doctor

Patient 1

Patient 2

Narrator/Background Speaker

Narrative:

1.  [Patient 1] - I’ve just got this kool new gadget that tracks all my
vital statistics and sends them to my doctor.
2.  [Patient 1] - Let me see if it even works.

1.  They bring their phone next to the NFC chip.
2.  The phone captures the temperature reading.
3.  The temperature shows on the device.

1.  [Patient 1] - Let me see if really works. Would the doctor even know
that i am sick? What would my doctor do if I was really sick? Let’s see
what happens when i accidentally (wink wink ...) drop this temperature
sensor in hot water.

1.  They drop the NFC chip in hot water.
2.  They bring their phone next to the NFC chip.
3.  The phone captures the temperature reading and it is really high.
4.  The temperature shows on the device.

1.  [Patient 1] - Oohh …. I have really high fever. I almost feel like I
have fever.

1.  Feel their head
2.  [Patient 1] - my head does feel a little warm. Am I really getting
sick?

1.  The scene shifts to the doctor who is sitting in their office
sipping coffee.

1.  Their desktop application displays an alert.
2.  [Doctor] - Oh my God. “Patient 1” is really sick - the temperature
reading is really high. I hope he is all right. They should rest and
immediately take some tylenol.

1.  [Doctor] - Let me send him a message and tell him that.

1.  The doctor navigates to “patient 1” by clicking on the alert in the
web application.
2.  The doctor sends a message to “patient 1”.

1.  “Doctor” types the message to the patient - “Your temperature is
really high. You should rest and immediately take some tylenol.”

1.  The scene shifts to “patient 1” who receives an alert in the
application letting them know “they have a new message from their
doctor”.
2.  [Patient 1] - “Doctor” sent me a new message. I wonder why he is
sending me a message at this hour.
3.  [Patient 1] - OMG! “Doctor” thinks that i have high fever. I’ll let
him know that i accidentally dropped the sensor in hot water. I doing
fine but thanks for checking in.

1.  They are a little embarrassed that this new technology really allows
the doctor to keep track of their health.

1.  Scene shifts to the doctor who has just read the message from
“patient 1”.
2.  [Doctor] - That was a false alarm. It would be really useful to
track pulse rate, blood pressure and oxygen level in addition to
temperature.
3.  [Doctor] - I wonder how long it will take IT to add these to the
application. I really hope they can do it in < 6 months.
4.  [Narrator] - IT gets a request that they need to support additional
user health data.
5.  [Narrator] - IT uses Couchbase Data platform that allows them to
make schema changes on the fly.
6.  [IT Guy] - I can add these additional health tracking data in no
time. I can really impress the whole team with how fast i can do this.
Would it be too cocky if i said that i already knew they were going to
ask for this? Hmm … let me be humble …
7.  [IT Guy] - Added new fields to the JSON document. (Big high fives
with someone?)
8.  [IT Guy] - Walks to doctor and let’s them know that their request
for more health data is done. If you choose the Couchbase data platform,
you can impress even the hard to please doctor. Punchline - TBD

1.  Patient 1 updates their app and sees the new health tracking data.

1.  [Patient 1] - Wow! They are tracking a lot more information about me
now. I feel like i am in good hands.

1.  Doctor checks the “health record” application and everything after
the addition of the new fields is tracking that data.

1.  [Doctor] - this is really great! Punchline about the IT department -
TBD
2.  [Doctor] - Let me send the results of the blood test to patient 2.

1.  Scene shifts to “patient 2” who receives a message on their phone
that their blood test report is now available.
2.  Patient 2 is boarding a flight and puts their phone in airplane
mode.
3.  [Patient 2] - I wonder if i can still access my blood test report.
Holy crap. This works even when i am flying across the atlantic with no
internet connectivity. “ABC Medical Group” is one of the most tech savvy
out there. ^link:#cmnt5[[e]]^

1.  Patient 2 sends a message to the doctor saying thank you for sending
the results.

1.  [Patient 2] - Flight has landed. Let me get out of airplane mode
2.  Scene shifts to the doctor. He receives an alert and clicks on it.
3.  [Doctor] - Patient 2 got the results and is mighty relieved
everything is alright.

link:#cmnt_ref5[[e]]Push relevant info with results (e.g. This is how to
understand CBC results.)
