#!/bin/bash

export script_home="$(cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"

source ${script_home}/initialize

source ${script_home}/options

until curl "http://${cluster_ip}:${admin_port}"
  do echo "waiting on admin console..."; sleep 2; done

${script_home}/server

until cbq -u "$COUCHBASE_RBAC_USERNAME" -p "$COUCHBASE_RBAC_PASSWORD" -s="\CONNECT ${cluster_url}" -q -exit-on-error
  do echo "waiting (cbq)..."; sleep 2; done

# Import data
${script_home}/import

# Configure N1QL query indexes
${script_home}/indexes

# Enable cURL in N1QL
${script_home}/curl -c ${config}/curl

# Configure full text search
${script_home}/fts -c ${config}/fts-index.json

# Configure analytics
${script_home}/analytics -c ${config}/analytics

# Configure eventing
${script_home}/eventing -c ${config}/eventing

# Start Sync Gateway
${script_home}/sync-gateway "SYNC_GATEWAY_CONFIG=${config}/sync-gateway-config.json" >& sg.log &

# Start web server
cd ${top_level}/web/server
${script_home}/app

# Configure Android
${script_home}/android